services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/<your-username>/<your-repo>
    branch: main
    dockerfilePath: ./backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: frontend
    env: docker
    repo: https://github.com/<your-username>/<your-repo>
    branch: main
    dockerfilePath: ./frontend/Dockerfile
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: NODE_ENV
        value: production
